# Generated by Django 4.2.5 on 2023-09-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="public_name",
            field=models.CharField(
                default="Amir", max_length=20, verbose_name="public name"
            ),
            preserve_default=False,
        ),
    ]
